allowBuilds:
  sharp: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.22'
  - '@better-auth/drizzle-adapter@1.6.22'
  - '@better-auth/kysely-adapter@1.6.22'
  - '@better-auth/memory-adapter@1.6.22'
  - '@better-auth/mongo-adapter@1.6.22'
  - '@better-auth/prisma-adapter@1.6.22'
  - '@better-auth/telemetry@1.6.22'
  - better-auth@1.6.22
  - mongoose@9.7.3
